# Libraries

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 
from functools import partial
from collections import Counter
import seaborn as sns

from joblib import load

# modeling
from sklearn import preprocessing, metrics
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold, RandomizedSearchCV
from sklearn.linear_model import LogisticRegressionCV, LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import recall_score, confusion_matrix
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler
from sklearn.utils import resample
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

# ignore warnings
import warnings
warnings.filterwarnings(action="ignore")

pd.set_option('display.max_columns', 1000)
pd.set_option('display.max_rows', 1000)

# Get dataset

In [2]:
# get pickle file
providers = load('./data/Providers_Third.pkl')

In [3]:
providers

PotentialFraud  Perc_Outpatient  DualPatientProvider  \
Provider                                                         
PRV51001               0         0.800000                  1.0   
PRV51003               1         0.530303                  1.0   
PRV51004               0         1.000000                  0.0   
PRV51005               1         1.000000                  0.0   
PRV51007               0         0.958333                  1.0   
...                  ...              ...                  ...   
PRV57759               0         1.000000                  0.0   
PRV57760               0         1.000000                  0.0   
PRV57761               0         1.000000                  0.0   
PRV57762               0         1.000000                  0.0   
PRV57763               0         1.000000                  0.0   

          Perc_DualPatientType  Ratio_ClaimsPerPatient  \
Provider                                                 
PRV51001              0.400000                1.041667   
PRV51003              0.500000                1.128205   
PRV51004              0.208054                1.079710   
PRV51005              0.248069                2.353535   
PRV51007              0.277778                1.241379   
...                        ...                     ...   
PRV57759              0.214286                1.166667   
PRV57760              0.363636                2.444444   
PRV57761              0.341463                1.223881   
PRV57762              1.000000                1.000000   
PRV57763              0.305085                1.685714   

          Ratio_ClaimsPerAttPhys  Perc_ClaimsPerTopFraudState  \
Provider                                                        
PRV51001                1.785714                          0.0   
PRV51003                3.000000                          0.0   
PRV51004                3.921053                          0.0   
PRV51005              194.166667                          0.0   
PRV51007                7.200000                          0.0   
...                          ...                          ...   
PRV57759               28.000000                          0.0   
PRV57760                7.333333                          0.0   
PRV57761               41.000000                          0.0   
PRV57762                1.000000                          0.0   
PRV57763              118.000000                          0.0   

          Perc_HasTop5AdmtCode  Perc_MultHospAttPhys  Perc_MultHospOperPhys  \
Provider                                                                      
PRV51001              0.040000              0.240000               0.040000   
PRV51003              0.060606              0.007576               0.000000   
PRV51004              0.013423              0.167785               0.013423   
PRV51005              0.032618              0.000000               0.000000   
PRV51007              0.027778              0.597222               0.083333   
...                        ...                   ...                    ...   
PRV57759              0.000000              0.000000               0.000000   
PRV57760              0.045455              0.000000               0.000000   
PRV57761              0.000000              0.000000               0.060976   
PRV57762              0.000000              0.000000               0.000000   
PRV57763              0.016949              0.000000               0.000000   

          Perc_MultHospOtherPhys  IP_Perc_Duplicates  IP_Count_UniquePatients  \
Provider                                                                        
PRV51001                0.000000            0.000000                      5.0   
PRV51003                0.000000            0.016129                     53.0   
PRV51004                0.000000            0.000000                      0.0   
PRV51005                0.000000            0.000000                      0.0   
PRV51007                0.027778    

# Train test split

In [4]:
# we want to normalize and down/upsample after splitting.
scores = providers.drop(['PotentialFraud'], axis=1)
scores = pd.DataFrame(scores, columns = scores.columns)
decision = providers["PotentialFraud"]

Xtrain, Xtest, ytrain, ytest = train_test_split(scores, decision, 
                                                test_size = .30, random_state=0, 
                                                stratify = decision)


# get splitted train set to df for upsampling
providers_trainTestSplit_train = pd.concat([ytrain, Xtrain], axis=1)
display(providers_trainTestSplit_train)
display(providers_trainTestSplit_train['PotentialFraud'].value_counts())

PotentialFraud  Perc_Outpatient  DualPatientProvider  \
Provider                                                         
PRV52041               1         1.000000                  0.0   
PRV51771               0         1.000000                  0.0   
PRV52079               0         0.787879                  1.0   
PRV55240               0         0.932515                  1.0   
PRV53417               1         0.959064                  1.0   
...                  ...              ...                  ...   
PRV53726               0         1.000000                  0.0   
PRV54226               0         1.000000                  0.0   
PRV56207               0         0.968421                  1.0   
PRV53427               0         1.000000                  0.0   
PRV52396               1         0.575000                  1.0   

          Perc_DualPatientType  Ratio_ClaimsPerPatient  \
Provider                                                 
PRV52041              0.245623                2.053377   
PRV51771              0.425000                1.176471   
PRV52079              0.272727                1.064516   
PRV55240              0.306748                1.124138   
PRV53417              0.315789                2.408451   
...                        ...                     ...   
PRV53726              0.562500                1.333333   
PRV54226              0.461538                1.181818   
PRV56207              0.252632                1.032609   
PRV53427              0.250000                1.411765   
PRV52396              0.575000                1.176471   

          Ratio_ClaimsPerAttPhys  Perc_ClaimsPerTopFraudState  \
Provider                                                        
PRV52041              235.625000                     0.037666   
PRV51771               40.000000                     1.000000   
PRV52079                1.500000                     0.000000   
PRV55240                3.975610                     0.079755   
PRV53417               17.100000                     0.000000   
...                          ...                          ...   
PRV53726                8.000000                     0.000000   
PRV54226                1.857143                     0.000000   
PRV56207                2.021277                     0.200000   
PRV53427                2.666667                     0.000000   
PRV52396                2.105263                     0.000000   

          Perc_HasTop5AdmtCode  Perc_MultHospAttPhys  Perc_MultHospOperPhys  \
Provider                                                                      
PRV52041              0.021751              0.115119               0.000000   
PRV51771              0.050000              0.000000               0.000000   
PRV52079              0.030303              0.090909               0.030303   
PRV55240              0.049080              0.165644               0.018405   
PRV53417              0.017544              0.105263               0.029240   
...                        ...                   ...                    ...   
PRV53726              0.062500              0.937500               0.062500   
PRV54226              0.076923              0.384615               0.000000   
PRV56207              0.042105              0.052632               0.021053   
PRV53427              0.041667              0.541667               0.041667   
PRV52396              0.100000              0.075000               0.025000   

          Perc_MultHospOtherPhys  IP_Perc_Duplicates  IP_Count_UniquePatients  \
Provider                                                                        
PRV52041                0.000000            0.000000                      0.0   
PRV51771                0.000000            0.000000                      0.0   
PRV52079                0.000000            0.142857                      7.0   
PRV55240                0.061350            0.090909                     11.0   
PRV53417                0.000000    

0    3433
1     354
Name: PotentialFraud, dtype: int64

# Upsampling

In [5]:
### UPSAMPLING
# Separate majority and minority classes
df_majority = providers_trainTestSplit_train[providers_trainTestSplit_train.PotentialFraud==0]
df_minority = providers_trainTestSplit_train[providers_trainTestSplit_train.PotentialFraud==1]

# Upsample minority class
df_minority_upsampled = resample(df_minority, 
                                 replace=True,     # sample with replacement
                                # to match majority class
                                 n_samples=providers_trainTestSplit_train['PotentialFraud'].value_counts()[0],
                                 random_state=0) # reproducible results

# Combine majority class with upsampled minority class
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

# Display new class counts
display(df_upsampled.PotentialFraud.value_counts())

# separate into Xtrain and Ytrain
Xtrain_upsampled = df_upsampled.drop(['PotentialFraud'], axis=1)
ytrain_upsampled = df_upsampled['PotentialFraud']

1    3433
0    3433
Name: PotentialFraud, dtype: int64

# Modeling

In [6]:
# Stratified Cross Validation needs to be applied 
skf = StratifiedKFold(n_splits = 3, random_state = 0, shuffle = True)

### 1. Logistic regression

In [7]:
logreg = LogisticRegression(random_state=0, class_weight='balanced', penalty='l1', solver='liblinear')

param_grid = {'C': np.logspace(-3,1,100)}

logregCV = GridSearchCV(logreg, 
                        param_grid = param_grid, 
                        scoring='recall',
                        cv=skf).fit(Xtrain,ytrain)

print("Best parameters: {}".format(logregCV.best_params_))
print("Best cross-validation score: {:.2f}".format(logregCV.best_score_))
print("Best estimator:\n{}".format(logregCV.best_estimator_))

print('--'*30)
print("Train recall score: {}".format(recall_score(ytrain, logregCV.best_estimator_.predict(Xtrain))))
print("Train recall score: {}".format(recall_score(ytest, logregCV.best_estimator_.predict(Xtest))))

print('--'*30)
print('Confusion matrix')
print(confusion_matrix(ytest,logregCV.predict(Xtest)))

Best parameters: {'C': 0.22051307399030456}
Best cross-validation score: 0.87
Best estimator:
LogisticRegression(C=0.22051307399030456, class_weight='balanced', penalty='l1',
                   random_state=0, solver='liblinear')
------------------------------------------------------------
Train recall score: 0.9180790960451978
Train recall score: 0.8881578947368421
------------------------------------------------------------
Confusion matrix
[[1278  193]
 [  17  135]]


### 2. Random forest

In [29]:
rf_param_grid = {
    'max_depth': range(1, 10), 
    'max_features': ['auto', 'log2'], 
    'min_samples_leaf': [4,5,6], 
    'min_samples_split': [1,2,3,4,5], 
    'n_estimators': [300,350,375,400]
}

rf_grid_search = RandomizedSearchCV(RandomForestClassifier(random_state=0, 
                                                  class_weight='balanced'), 
                                    param_distributions=rf_param_grid, cv=skf, scoring='recall', 
                                    random_state=0, return_train_score=True)
rf_grid_search.fit(Xtrain, ytrain)


print("Best parameters: {}".format(rf_grid_search.best_params_))
print("Best cross-validation score: {:.2f}".format(rf_grid_search.best_score_))
print("Best estimator:\n{}".format(rf_grid_search.best_estimator_))

print('--'*30)
print("Train recall score: {}".format(recall_score(ytrain, rf_grid_search.best_estimator_.predict(Xtrain))))
print("Train recall score: {}".format(recall_score(ytest, rf_grid_search.best_estimator_.predict(Xtest))))

print('--'*30)
print('Confusion matrix')
print(confusion_matrix(ytest,rf_grid_search.predict(Xtest)))

Best parameters: {'n_estimators': 350, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 'auto', 'max_depth': 3}
Best cross-validation score: 0.86
Best estimator:
RandomForestClassifier(class_weight='balanced', max_depth=3, min_samples_leaf=5,
                       min_samples_split=5, n_estimators=350, random_state=0)
------------------------------------------------------------
Train recall score: 0.9096045197740112
Train recall score: 0.9013157894736842
------------------------------------------------------------
Confusion matrix
[[1235  236]
 [  15  137]]


### 3. Support vector machine

In [9]:
svm_param_grid = {'C': np.logspace(-3,1,100)}

svm_rand_search = RandomizedSearchCV(SVC(random_state=0, class_weight='balanced'),
                                     svm_param_grid, 
                                     cv=skf, 
                                     scoring='recall')
svm_rand_search.fit(Xtrain, ytrain)

print("Best parameters: {}".format(svm_rand_search.best_params_))
print("Best cross-validation score: {:.2f}".format(svm_rand_search.best_score_))
print("Best estimator:\n{}".format(svm_rand_search.best_estimator_))

print('--'*30)
print("Train recall score: {}".format(recall_score(ytrain, svm_rand_search.best_estimator_.predict(Xtrain))))
print("Train recall score: {}".format(recall_score(ytest, svm_rand_search.best_estimator_.predict(Xtest))))

print('--'*30)
print('Confusion matrix')
print(confusion_matrix(ytest,svm_rand_search.predict(Xtest)))

Best parameters: {'C': 0.004862601580065354}
Best cross-validation score: 0.87
Best estimator:
SVC(C=0.004862601580065354, class_weight='balanced', random_state=0)
------------------------------------------------------------
Train recall score: 0.867231638418079
Train recall score: 0.8552631578947368
------------------------------------------------------------
Confusion matrix
[[1046  425]
 [  22  130]]


### 4. Gaussian Naive Bayes

In [10]:
gnb_param_grid = {'var_smoothing': np.logspace(-30,1,100)}

gnb_rand_search = RandomizedSearchCV(GaussianNB(),
                                     gnb_param_grid, 
                                     cv=skf, 
                                     scoring='recall')
gnb_rand_search.fit(Xtrain, ytrain)

print("Best parameters: {}".format(gnb_rand_search.best_params_))
print("Best cross-validation score: {:.2f}".format(gnb_rand_search.best_score_))
print("Best estimator:\n{}".format(gnb_rand_search.best_estimator_))

print('--'*30)
print("Train recall score: {}".format(recall_score(ytrain, gnb_rand_search.best_estimator_.predict(Xtrain))))
print("Train recall score: {}".format(recall_score(ytest, gnb_rand_search.best_estimator_.predict(Xtest))))

print('--'*30)
print('Confusion matrix')
print(confusion_matrix(ytest,gnb_rand_search.predict(Xtest)))

Best parameters: {'var_smoothing': 2.8480358684357933e-22}
Best cross-validation score: 0.82
Best estimator:
GaussianNB(var_smoothing=2.8480358684357933e-22)
------------------------------------------------------------
Train recall score: 0.8192090395480226
Train recall score: 0.8092105263157895
------------------------------------------------------------
Confusion matrix
[[1233  238]
 [  29  123]]


In [11]:
gnb_param_grid = {'var_smoothing': np.logspace(-10,1,100)}

gnb_rand_search = RandomizedSearchCV(GaussianNB(),
                                     gnb_param_grid, 
                                     cv=skf, 
                                     scoring='recall')
gnb_rand_search.fit(Xtrain_upsampled, ytrain_upsampled)

print("Best parameters: {}".format(gnb_rand_search.best_params_))
print("Best cross-validation score: {:.2f}".format(gnb_rand_search.best_score_))
print("Best estimator:\n{}".format(gnb_rand_search.best_estimator_))

print('--'*30)
print("Train recall score: {}".format(recall_score(ytrain_upsampled, 
                                                   gnb_rand_search.best_estimator_.predict(Xtrain_upsampled))))
print("Train recall score: {}".format(recall_score(ytest, gnb_rand_search.best_estimator_.predict(Xtest))))

print('--'*30)
print('Confusion matrix')
print(confusion_matrix(ytest,gnb_rand_search.predict(Xtest)))

Best parameters: {'var_smoothing': 2.1544346900318866e-09}
Best cross-validation score: 0.80
Best estimator:
GaussianNB(var_smoothing=2.1544346900318866e-09)
------------------------------------------------------------
Train recall score: 0.8054180017477425
Train recall score: 0.7828947368421053
------------------------------------------------------------
Confusion matrix
[[1326  145]
 [  33  119]]


### 5. KNN

In [12]:
knn_param_grid = {'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                  'leaf_size': [10,30,50],
                  'n_neighbors': [3,5,7],
                  'weights': ['uniform', 'distance']
                 }

knn_rand_search = RandomizedSearchCV(KNeighborsClassifier(),
                                     knn_param_grid, 
                                     cv=skf, 
                                     scoring='recall')
knn_rand_search.fit(Xtrain, ytrain)

print("Best parameters: {}".format(knn_rand_search.best_params_))
print("Best cross-validation score: {:.2f}".format(knn_rand_search.best_score_))
print("Best estimator:\n{}".format(knn_rand_search.best_estimator_))

print('--'*30)
print("Train recall score: {}".format(recall_score(ytrain, knn_rand_search.best_estimator_.predict(Xtrain))))
print("Train recall score: {}".format(recall_score(ytest, knn_rand_search.best_estimator_.predict(Xtest))))

print('--'*30)
print('Confusion matrix')
print(confusion_matrix(ytest,knn_rand_search.predict(Xtest)))

Best parameters: {'weights': 'uniform', 'n_neighbors': 3, 'leaf_size': 50, 'algorithm': 'brute'}
Best cross-validation score: 0.29
Best estimator:
KNeighborsClassifier(algorithm='brute', leaf_size=50, n_neighbors=3)
------------------------------------------------------------
Train recall score: 0.5988700564971752
Train recall score: 0.4342105263157895
------------------------------------------------------------
Confusion matrix
[[1410   61]
 [  86   66]]


In [13]:
knn_param_grid = {'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                  'leaf_size': [10,30,50],
                  'n_neighbors': [3,5,7],
                  'weights': ['uniform', 'distance']
                 }

knn_rand_search = RandomizedSearchCV(KNeighborsClassifier(),
                                     knn_param_grid, 
                                     cv=skf, 
                                     scoring='recall')
knn_rand_search.fit(Xtrain_upsampled, ytrain_upsampled)

print("Best parameters: {}".format(knn_rand_search.best_params_))
print("Best cross-validation score: {:.2f}".format(knn_rand_search.best_score_))
print("Best estimator:\n{}".format(knn_rand_search.best_estimator_))

print('--'*30)
print("Train recall score: {}".format(recall_score(ytrain_upsampled,
                                                   knn_rand_search.best_estimator_.predict(Xtrain_upsampled))))
print("Train recall score: {}".format(recall_score(ytest, knn_rand_search.best_estimator_.predict(Xtest))))

print('--'*30)
print('Confusion matrix')
print(confusion_matrix(ytest,knn_rand_search.predict(Xtest)))

Best parameters: {'weights': 'distance', 'n_neighbors': 3, 'leaf_size': 30, 'algorithm': 'auto'}
Best cross-validation score: 1.00
Best estimator:
KNeighborsClassifier(n_neighbors=3, weights='distance')
------------------------------------------------------------
Train recall score: 1.0
Train recall score: 0.6052631578947368
------------------------------------------------------------
Confusion matrix
[[1317  154]
 [  60   92]]


### 6. Gradient boosting

In [15]:
gb = GradientBoostingClassifier(random_state = 0, max_depth = 2)
gb_param_grid = {'n_estimators': [500,1000,2000,2500,3000],
                'max_features': [10,13,15,20],
                'learning_rate': [0.005, 0.01, 0.015, 0.02],
                    'min_samples_split': [17,20,25],
                    'min_samples_leaf' : [17,20,25]}

gb_rand_search = RandomizedSearchCV(gb, 
                                    gb_param_grid, 
                                    cv= skf, 
                                    n_jobs = 5, 
                                    verbose = 1,
                                    return_train_score = True,
                                    scoring = 'recall')

gb_rand_search.fit(Xtrain, ytrain)

print("Best parameters: {}".format(gb_rand_search.best_params_))
print("Best cross-validation score: {:.2f}".format(gb_rand_search.best_score_))
print("Best estimator:\n{}".format(gb_rand_search.best_estimator_))

print('--'*30)
print("Train recall score: {}".format(recall_score(ytrain, gb_rand_search.best_estimator_.predict(Xtrain))))
print("Train recall score: {}".format(recall_score(ytest, gb_rand_search.best_estimator_.predict(Xtest))))

print('--'*30)
print('Confusion matrix')
print(confusion_matrix(ytest,gb_rand_search.predict(Xtest)))

Fitting 3 folds for each of 10 candidates, totalling 30 fits


[Parallel(n_jobs=5)]: Using backend LokyBackend with 5 concurrent workers.
[Parallel(n_jobs=5)]: Done  30 out of  30 | elapsed:   39.9s finished


Best parameters: {'n_estimators': 3000, 'min_samples_split': 25, 'min_samples_leaf': 25, 'max_features': 20, 'learning_rate': 0.01}
Best cross-validation score: 0.53
Best estimator:
GradientBoostingClassifier(learning_rate=0.01, max_depth=2, max_features=20,
                           min_samples_leaf=25, min_samples_split=25,
                           n_estimators=3000, random_state=0)
------------------------------------------------------------
Train recall score: 0.7655367231638418
Train recall score: 0.5131578947368421
------------------------------------------------------------
Confusion matrix
[[1445   26]
 [  74   78]]


In [19]:
gb = GradientBoostingClassifier(random_state = 0, max_depth = 2)
gb_param_grid = {'n_estimators': [3000,3100,3200,3250],
                'max_features': [19,20,21],
                'learning_rate': [0.03,0.035,0.04],
                    'min_samples_split': [25,26,27,28],
                    'min_samples_leaf' : [14,15,16]}

gb_rand_search = RandomizedSearchCV(gb, 
                                    gb_param_grid, 
                                    cv= skf, 
                                    n_jobs = 5, 
                                    verbose = 1,
                                    return_train_score = True,
                                    scoring = 'recall')

gb_rand_search.fit(Xtrain_upsampled, ytrain_upsampled)

print("Best parameters: {}".format(gb_rand_search.best_params_))
print("Best cross-validation score: {:.2f}".format(gb_rand_search.best_score_))
print("Best estimator:\n{}".format(gb_rand_search.best_estimator_))

print('--'*30)
print("Train recall score: {}".format(recall_score(ytrain_upsampled,
                                                   gb_rand_search.best_estimator_.predict(Xtrain_upsampled))))
print("Train recall score: {}".format(recall_score(ytest, gb_rand_search.best_estimator_.predict(Xtest))))

print('--'*30)
print('Confusion matrix')
print(confusion_matrix(ytest,gb_rand_search.predict(Xtest)))

Fitting 3 folds for each of 10 candidates, totalling 30 fits


[Parallel(n_jobs=5)]: Using backend LokyBackend with 5 concurrent workers.
[Parallel(n_jobs=5)]: Done  30 out of  30 | elapsed:  2.5min finished


Best parameters: {'n_estimators': 3200, 'min_samples_split': 27, 'min_samples_leaf': 15, 'max_features': 20, 'learning_rate': 0.04}
Best cross-validation score: 1.00
Best estimator:
GradientBoostingClassifier(learning_rate=0.04, max_depth=2, max_features=20,
                           min_samples_leaf=15, min_samples_split=27,
                           n_estimators=3200, random_state=0)
------------------------------------------------------------
Train recall score: 1.0
Train recall score: 0.6710526315789473
------------------------------------------------------------
Confusion matrix
[[1420   51]
 [  50  102]]
